import { useRouter } from "next/router";
import { useEffect, useState } from "react";

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Button, Form, Divider, Input, Modal, TextArea, Icon, Header, Segment } from "semantic-ui-react";
import styles from '@/styles/Home.module.css'
import baseStyles from "/src/component/css/Base.module.css";
// import styles from "/src/component/css/Base.module.css";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>




      <div
        style={{
          width: "30%",
          height: "800px",
          display: "flex",
          paddingTop: 10,
          backgroundColor: "#154360",
          border: "1px solid white",
          justifyContent: "space-between"

        }}
      >
        <div style={{ display: "flex", justifyContent: "left" }}>
          <div style={{
            paddingTop: 10,
            paddingLeft: 30,
            padding: 10,
            // border: "2px dashed red",
          }}>

          </div>
          <div style={{
            flex: "600px 0 0",
            padding: 20,
            fontWeight: "bold",
            fontSize: 30,
            color: "#FF6800",
            // border: "2px dashed red",
          }}>
            좌측 메뉴
          </div>
        </div>
      </div>








      {/* <div className={baseStyles.exlayout}>
        <div className={baseStyles.gnb}>Global menu</div>
        <div className={baseStyles.main}>
          <div className={baseStyles.lnb}>Left menu</div>
          <div className={baseStyles.content}>
            Content areaContent areaContent areaContent areaContent areaContent area
          </div>
        </div>
      </div> */}

    </>
  )
}
