/* eslint-disable @next/next/no-img-element */
// import Gnb from "./Gnb";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Head from "next/head";
import { Button, Form, Divider, Input, Label, Image, Icon } from "semantic-ui-react";

export default function Top() {
    const router = useRouter();

    useEffect(() => {
    }, []);

    return (
        <div>
            <Head>
                <title></title>
                <meta name="description" content="Generated by EmartDT" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div
                style={{
                    display: "flex",
                    paddingTop: 10,
                    backgroundColor: "#D6DBDF ",
                    // borderRadius: 5,
                    border: "1px solid white",
                    justifyContent: "space-between"

                }}
            >
                <div style={{ display: "flex", justifyContent: "left" }}>
                    <div style={{
                        paddingTop: 10,
                        paddingLeft: 30,
                        padding: 10,
                        // border: "2px dashed red",
                    }}>

                    </div>
                    <div style={{
                        flex: "600px 0 0",
                        padding: 20,
                        fontWeight: "bold",
                        fontSize: 20,
                        color: "#212F3D",
                        // border: "2px dashed red",
                    }}>
                        ChatGPT Blog Page Generator
                    </div>
                </div>
                <div
                    style={{
                        padding: 20,
                        // border: "2px dashed red",
                    }}
                >
                    <>
                        <Label>
                            <Icon name='user' />
                        </Label>
                        <Label as='a' image>
                            <Icon name='sign-out alternate' /> 로그아웃
                        </Label>
                    </>
                </div>
            </div>
            {/* <Gnb /> */}
        </div>
    );
}
